# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWY4MmVhOGZkNWIzYzcwMGU2MmE4NDUwZDNkNmY3NzQ1OWE0NGM1Mzc5ZGU4MGU4MTQ3ZGZkNGM4NzBjMjhjY2M1NDU5MTZjZTQ0MWZkNDc3MzlkN2M5MjcwNzY2Yzc3MjkyNDY2MjM2NzNiNmZjYWM4YjNlMmMxNzMzNDg5Mjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
