# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MzdhNjUxZGNkOTdlMzI2MTkyMjIyNWY0NTQwZGEyMGIxYmI0ZDQyNGNiYTQwODA2NzhhYWYzYzhlOWU4Y2IzYzY1MTBiNWNlYWI4ODgwZDM1NjliMzFmMmRmNWVlNWNhNGJkN2U3OGRkMjAwMDdiZWU5MzZlNjM5OTE2MWQ0MjA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
